# Key Bindings
# key name refer to `xev` or `wev` command output,
# mod keys name: super,ctrl,alt,shift,none

# Set specific layout
bind=SUPER,t,setlayout,tile
bind=SUPER,s,setlayout,scroller
bind=SUPER,m,setlayout,monocle

# reload config
bind=SUPER,r,reload_config

# menu and terminal
bind=SUPER,p,spawn,rofi -show run
bind=SUPER+SHIFT,Return,spawn,foot

# screenshot
bind=SUPER,Print,spawn,dms screenshot

# sound
bind=None,XF86AudioRaiseVolume,spawn,dms ipc call audio increment 5
bind=None,XF86AudioLowerVolume,spawn,dms ipc call audio decrement 5
bind=None,XF86AudioMute,spawn,dms ipc call audio mute

# brightness
bind=None,XF86MonBrightnessUp,spawn,dms ipc call brightness increment 5 ""
bind=None,XF86MonBrightnessDown,spawn,dms ipc call brightness decrement 5 ""

# lock
bind=SUPER,Escape,spawn,dms ipc call lock lock

# exit
bind=SUPER+SHIFT,q,quit
bind=SUPER+SHIFT,c,killclient,

# switch window focus
bind=SUPER,j,focusstack,next
bind=SUPER,k,focusstack,prev

# swap window
bind=SUPER+SHIFT,j,exchange_stack_client,next
bind=SUPER+SHIFT,k,exchange_stack_client,prev
bind=SUPER+SHIFT,h,exchange_client,left
bind=SUPER+SHIFT,l,exchange_client,right

# switch window status
bind=SUPER,g,toggleglobal,
bind=SUPER,Tab,toggleoverview,
bind=SUPER,backslash,togglefloating,
bind=SUPER,a,togglemaximizescreen,
bind=SUPER,f,togglefullscreen,
# bind=ALT+SHIFT,f,togglefakefullscreen,
bind=SUPER,i,minimized,
bind=SUPER,o,toggleoverlay,
bind=SUPER+SHIFT,I,restore_minimized
bind=SUPER,z,toggle_scratchpad

# scroller layout
bind=SUPER,e,set_proportion,1.0
bind=SUPER,x,switch_proportion_preset,

# switch layout
bind=SUPER,Space,switch_layout

# tag switch
bind=SUPER,Left,viewtoleft,0
bind=CTRL,Left,viewtoleft_have_client,0
bind=SUPER,Right,viewtoright,0
bind=CTRL,Right,viewtoright_have_client,0
bind=CTRL+SUPER,Left,tagtoleft,0
bind=CTRL+SUPER,Right,tagtoright,0

bind=SUPER,1,view,1,0
bind=SUPER,2,view,2,0
bind=SUPER,3,view,3,0
bind=SUPER,4,view,4,0
bind=SUPER,5,view,5,0
bind=SUPER,6,view,6,0
bind=SUPER,7,view,7,0
bind=SUPER,8,view,8,0
bind=SUPER,9,view,9,0

bind=SUPER+CTRL,1,toggleview,1,0
bind=SUPER+CTRL,2,toggleview,2,0
bind=SUPER+CTRL,3,toggleview,3,0
bind=SUPER+CTRL,4,toggleview,4,0
bind=SUPER+CTRL,5,toggleview,5,0
bind=SUPER+CTRL,6,toggleview,6,0
bind=SUPER+CTRL,7,toggleview,7,0
bind=SUPER+CTRL,8,toggleview,8,0
bind=SUPER+CTRL,9,toggleview,9,0

# tag: move client to the tag and focus it
# tagsilent: move client to the tag and not focus it
# bind=Alt,1,tagsilent,1
bind=SUPER+SHIFT,1,tagsilent,1,0
bind=SUPER+SHIFT,2,tagsilent,2,0
bind=SUPER+SHIFT,3,tagsilent,3,0
bind=SUPER+SHIFT,4,tagsilent,4,0
bind=SUPER+SHIFT,5,tagsilent,5,0
bind=SUPER+SHIFT,6,tagsilent,6,0
bind=SUPER+SHIFT,7,tagsilent,7,0
bind=SUPER+SHIFT,8,tagsilent,8,0
bind=SUPER+SHIFT,9,tagsilent,9,0

# monitor switch
bind=alt+shift,Left,focusmon,left
bind=alt+shift,Right,focusmon,right
bind=SUPER+Alt,Left,tagmon,left
bind=SUPER+Alt,Right,tagmon,right

# gaps
bind=ALT+SHIFT,X,incgaps,1
bind=ALT+SHIFT,Z,incgaps,-1
bind=ALT+SHIFT,R,togglegaps

# movewin
bind=CTRL+SHIFT,Up,movewin,+0,-50
bind=CTRL+SHIFT,Down,movewin,+0,+50
bind=CTRL+SHIFT,Left,movewin,-50,+0
bind=CTRL+SHIFT,Right,movewin,+50,+0

# resizewin
bind=CTRL+ALT,Up,resizewin,+0,-50
bind=CTRL+ALT,Down,resizewin,+0,+50
bind=CTRL+ALT,Left,resizewin,-50,+0
bind=CTRL+ALT,Right,resizewin,+50,+0

# Mouse Button Bindings
# btn_left and btn_right can't bind none mod key
mousebind=SUPER,btn_left,moveresize,curmove
mousebind=SUPER,btn_right,moveresize,curresize

# Swipe Gesture Bindings
gesturebind=none,right,3,spawn,wtype -M alt -P Left -p Left -m alt
gesturebind=none,left,3,spawn,wtype -M alt -P Right -p Right -m alt

# Axis Bindings
axisbind=SUPER,UP,viewtoleft_have_client
axisbind=SUPER,DOWN,viewtoright_have_client
