# Import configuration files
source=./config/startup.conf
source=./config/layout.conf
source=./config/bind.conf
source=./config/theme.conf
source=./config/settings.conf

# Optional configuration
source-optional=./optional.conf
